package javaproject_1;


import javaproject_1.Ventana1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Diego A. Vivolo
 */
public class VentanaOpcion extends javax.swing.JFrame {
    
    public static Ventana1 v1;

    /**
     * Creates new form Ventana_opcion
     */
    public VentanaOpcion(Ventana1 v1) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gestionCiudad = new javax.swing.JButton();
        startsim = new javax.swing.JButton();
        cargarG = new javax.swing.JButton();
        ajustes_Iniciales = new javax.swing.JButton();
        saveGrafo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 308, -1, -1));

        gestionCiudad.setText("Gestion de Ciudades");
        gestionCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(gestionCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 220, 60));

        startsim.setText("Comenzar simulacion ");
        startsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startsimActionPerformed(evt);
            }
        });
        getContentPane().add(startsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 220, 60));

        cargarG.setText("Cargar Archivo");
        getContentPane().add(cargarG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 220, 60));

        ajustes_Iniciales.setText("Ajustes Iniciales");
        ajustes_Iniciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajustes_InicialesActionPerformed(evt);
            }
        });
        getContentPane().add(ajustes_Iniciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 60));

        saveGrafo.setText("Guardar Archivo");
        saveGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(saveGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 220, 60));

        jLabel1.setText("Ant System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jButton1.setText("Agregar Ciudad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 220, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startsimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startsimActionPerformed

    private void gestionCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionCiudadActionPerformed

    private void saveGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGrafoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveGrafoActionPerformed

    private void ajustes_InicialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajustes_InicialesActionPerformed
        VentanaAjuste vA = new VentanaAjuste(this);
    }//GEN-LAST:event_ajustes_InicialesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaOpcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaOpcion(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajustes_Iniciales;
    private javax.swing.JButton cargarG;
    private javax.swing.JButton gestionCiudad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveGrafo;
    private javax.swing.JButton startsim;
    // End of variables declaration//GEN-END:variables
}
